using System.Text;

namespace SolutionMapper.DiffTools;

/// <summary>
/// Resolves the WinMerge folder-comparison filter that hides build output and IDE cruft
/// (<c>bin</c>, <c>obj</c>, <c>.vs</c>, binaries, per-user files). Prefers WinMerge's own
/// built-in "Visual C# loose" filter; falls back to a generated equivalent so portable
/// installs that ship no filters still get the exclusions.
/// </summary>
public static class WinMergeFilter
{
    /// <summary>The built-in filter's <c>name:</c>, as accepted by <c>/f</c> and a project's <c>&lt;filter&gt;</c>.</summary>
    public const string BuiltInName = "Visual C# loose";

    // Same rules as WinMerge's CSharp_loose.flt, kept self-contained.
    const string GeneratedContent = """
        ## Generated by SolutionMapper — suppresses build output and IDE files in C# trees
        name: SolutionMapper C# loose
        desc: Suppresses bin, obj, .vs, binaries and per-user files

        def: include

        f: \.aps$
        f: \.bsc$
        f: \.dll$
        f: \.exe$
        f: \.obj$
        f: \.pdb$
        f: \.res$
        f: \.suo$
        f: \.user$
        f: \.cache$
        f: \.bak$

        d: \\bin$
        d: \\obj$
        d: \\\.vs$
        d: \\\.git$
        d: \\\.svn$
        d: \\packages$
        d: \\TestResults$
        """;

    /// <summary>
    /// The value to hand WinMerge: the built-in filter name when its <c>.flt</c> is installed
    /// next to <paramref name="winMergeExe"/>, otherwise a path to the generated fallback file.
    /// </summary>
    public static string Resolve(string winMergeExe)
    {
        var installDir = Path.GetDirectoryName(winMergeExe);
        if (installDir is not null)
        {
            var builtIn = Path.Combine(installDir, "Filters", "CSharp_loose.flt");
            if (File.Exists(builtIn))
                return BuiltInName;
        }

        return WriteGenerated();
    }

    static string WriteGenerated()
    {
        var dir = Path.Combine(Path.GetTempPath(), "SolutionMapper");
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, "SolutionMapper-CSharp-loose.flt");
        File.WriteAllText(path, GeneratedContent.ReplaceLineEndings("\r\n"), new UTF8Encoding(false));
        return path;
    }
}
